### ISSUE TITLE
Slow file opening

### ISSUE THREAD

**Issue by Caceresenzo** [swdotcom/swdc-eclipse-codetime#14]
Hi,

Eclipse can take up to one second to open a file.
This is especially annoying when just looking for a piece of code.

Uninstalling the plugin '''solve''' this issue.

**Comment by xavluiz** [comment]
We'll look into this right away.
Regards.

**Comment by xavluiz** [comment]
We've removed a line count that happens when a file opens, along with optimizing other logic around this area. The new version is 2.2.24.

Thank you.

**Comment by Caceresenzo** [comment]
Everything is much faster now, thanks you.
